# Generated by Django 4.1.2 on 2022-10-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
