# Generated by Django 4.1.2 on 2022-10-13 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_1', '0003_alter_address_options_remove_address_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
